name: test_djelme

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-py
        with:
          python-version: '3.7'
      - run: pip install -U tox
      - name: alias pythonX.Y for tox
        run: alias python${{ steps.setup-py.outputs.python-version }}=${{ steps.setup-py.outputs.python-path }}
      - run: TOXENV=lint tox


  test:
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9', '3.10']
        django: ['1.11', '2.0', '2.1', '2.2', '3.0', '3.1', '3.2', '4.0', '4.1']
        os: ['ubuntu-latest', 'ubuntu-20.04']
        # TODO: elasticsearch: ['6', '7', '8', '9']
        exclude:
          - {os: 'ubuntu-20.04', python: '3.7'}
          - {os: 'ubuntu-20.04', python: '3.8'}
          - {os: 'ubuntu-20.04', python: '3.9'}
          - {os: 'ubuntu-20.04', python: '3.10'}
          - {os: 'ubuntu-latest', python: '3.6'}
          - {python: '3.6', django: '4.0'}
          - {python: '3.6', django: '4.1'}
          - {python: '3.7', django: '4.0'}
          - {python: '3.7', django: '4.1'}
          - {python: '3.10', django: '1.11'}
          - {python: '3.10', django: '2.0'}
    runs-on: ${{ matrix.os }}
    services:
      elasticsearch:
        image: elasticsearch:6.8.23
        ports:
          - 9201:9200
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-py
        with:
          python-version: ${{ matrix.python }}
      - run: pip install -U tox
      - run: alias python${{ steps.setup-py.outputs.python-version }}=${{ steps.setup-py.outputs.python-path }}
      - run: TOXENV=`echo 'py${{ matrix.python }}-django${{matrix.django}}' | sed 's/\.//g'` tox

